#! /bin/bash

#Authors: Jan-Åke Larsson and Jonathan Jogenfors

revision=
while test $# -ne 0; do
    case "$1" in
        "-r")
            shift
            revision=$1
            ;;
        *)
            src=${1%.tex}
            ;;
    esac
    shift
done

if [ -z "$src" ]; then
    MAINFILES=$(ls *.tex.latexmain)
    if [ -z "$MAINFILES" ]; then
        echo "No latexmain found"
        exit 1
    fi

    src=$(basename -s .tex.latexmain $MAINFILES)
fi

if [ -z "$revision" ]; then
	revision=$(git log --skip=1 -n 1 --pretty=format:%h -- $src.tex)
fi

TEMPDIR=$(mktemp -dt latexdiff.XXXXXXX)

OLDFILE=$TEMPDIR/$src.old.tex
DIFFILE=$TEMPDIR/$src.diff.tex

echo $src.tex
echo $OLDFILE
echo $DIFFILE


#git show $revision:./$src.tex > $OLDFILE
latexdiff $OLDFILE $src.tex > $DIFFILE
latexmk -pdf $DIFFILE
evince $(basename -s .tex $DIFFILE).pdf
